
# Adding Explanatory Variables (coming soon!)

This example shows what happens to the regression model when additional explanatory variable are included. Using rotations of the original model allows you to replicate the coefficients from a nested model. There are two benefits to using rotations instead of dropping variables to create nested models.

  1. The standard error for the marginal effect of the rotated axes tends to be more precise than the standard error attached to that axis on a nested model.
  2. Using the rotation allows you to control for all variables in the model instead of "biasing" them by creating a joint direction between those omitted variable(s) and the included variables.

In particular, for any new coefficient $x_i$, the coefficient on $x_i$ in the estimated regression surface is interpreted as the marginal effect holding all other variables constant including $x_1$ and $x_2$. The interpretation of the coefficient on $x_i$ remains the same for any model that uses a rotation of $x_1$ and $x_2$. This stands in contrast to nested models, because dropping a variable produces a joint direction between all coefficients and the excluded variable(s), not just the joint change for two variables.  That is, nested models give you flexibility in the direction you want to examine the changes in $x_1$ and $x_2$. Rotated models allow the same flexibility and more, while still controlling for all variables in the original model.

The data in this example shows...

